

export const MODULE_GLOBAL = '$$global';
export const MODULE_DEFAULT = '$$default';
export const MODULE_CC = '$$cc';
export const MODULE_CC_ROUTER = '$$CONCENT_ROUTER';

export const CC_FRAGMENT_PREFIX = '$$Fragment';
export const CC_DISPATCHER = '$$Dispatcher';
export const CC_DISPATCHER_BOX = '__cc_dispatcher_container_designed_by_zzk_qq_is_624313307__';

export const  CURSOR_KEY = Symbol('__for_sync_param_cursor__');
export const  CCSYNC_KEY = Symbol('__for_sync_param_ccsync__');
export const  MOCKE_KEY = Symbol('__for_mock_event__');
export const  LAZY_KEY = Symbol('__lazy_handle_state__');

export const SIG_FN_START = 10;
export const SIG_FN_END = 11;
export const SIG_FN_QUIT = 12;
export const SIG_FN_ERR = 13;

export const STATE_FOR_ONE_CC_INSTANCE_FIRSTLY = 1;
export const STATE_FOR_ALL_CC_INSTANCES_OF_ONE_MODULE = 2;

export const EFFECT_AVAILABLE = 1;
export const EFFECT_STOPPED = 0;

export const DISPATCH = 'dispatch';
export const SET_STATE = 'setState';
export const SET_MODULE_STATE = 'setModuleState';
export const FORCE_UPDATE = 'forceUpdate';
export const INVOKE = 'invoke';
export const SYNC = 'sync';

export const ERR = {
  CC_ALREADY_STARTUP: 1000,
  CC_REGISTER_A_MODULE_CLASS_IN_NONE_MODULE_MODE: 1001,
  CC_MODULE_NAME_DUPLICATE: 1002,
  CC_REGISTER_A_CC_CLASS: 1003,
  CC_MODULE_KEY_CC_FOUND: 1004,
  CC_MODULE_NAME_INVALID: 1005,
  CC_STORE_STATE_INVALID: 1006,
  CC_MODULE_REDUCER_IN_CC_CONFIGURE_OPTION_IS_INVALID: 1008,
  CC_REDUCER_IN_CC_CONFIGURE_OPTION_IS_INVALID: 1009,
  CC_REDUCER_VALUE_IN_CC_CONFIGURE_OPTION_IS_INVALID: 1010,
  CC_MODULE_NOT_FOUND: 1012,
  CC_DISPATCH_STRING_INVALID: 1013,
  CC_DISPATCH_PARAM_INVALID: 1014,
  CC_NO_DISPATCHER_FOUND: 1015,
  CC_WATCH_MODULE_INVALID_IN_STARTUP_OPTION: 1016,
  CC_MODULE_NAME_HAS_NO_STATE:1017,

  CC_CLASS_KEY_DUPLICATE: 1100,
  CC_CLASS_NOT_FOUND: 1101,
  CC_CLASS_STORE_MODULE_INVALID: 1102,
  CC_CLASS_REDUCER_MODULE_INVALID: 1104,
  CC_CLASS_IS_NOT_ALLOWED_REGISTER_TO_A_SINGLE_CLASS_MODULE:1106,
  CC_CLASS_STATE_TO_PROP_MAPPING_INVALID:1107,
  CC_CLASS_KEY_FRAGMENT_NOT_ALLOWED:1108,

  CC_CLASS_INSTANCE_KEY_DUPLICATE: 1200,
  CC_CLASS_INSTANCE_OPTION_INVALID: 1201,
  CC_CLASS_INSTANCE_NOT_FOUND: 1202,
  CC_CLASS_INSTANCE_METHOD_NOT_FOUND: 1203,
  CC_CLASS_INSTANCE_CALL_WITH_ARGS_INVALID: 1204,
  CC_CLASS_INSTANCE_MORE_THAN_ONE: 1205,
  CC_CLASS_INSTANCE_NO_CC_KEY_SPECIFIED_WHEN_USE_STORED_KEYS: 1207,
  
  CC_ARG_STORED_KEYS_DUPLICATE_WITH_WATCHED_KEYS: 1401,
  CC_ARG_KEYS_NOT_AN_ARRAY: 1402,
  CC_ARG_KEYS_INCLUDE_NON_STRING_ELEMENT: 1403,

  CC_REDUCER_ACTION_TYPE_NAMING_INVALID: 1500,
  CC_REDUCER_ACTION_TYPE_DUPLICATE: 1501,
  CC_REDUCER_ACTION_TYPE_NO_MODULE: 1502,
  CC_REDUCER_NOT_A_FUNCTION: 1503,
  CC_REDUCER_MODULE_NAME_DUPLICATE: 1511,
  // REDUCER_KEY_NOT_EXIST_IN_STORE_MODULE: 1203,
}

export const ERR_MESSAGE = {
  [ERR.CC_ALREADY_STARTUP]: '1',
  [ERR.CC_REGISTER_A_MODULE_CLASS_IN_NONE_MODULE_MODE]: '1',
  [ERR.CC_MODULE_NAME_DUPLICATE]: '1',
  [ERR.CC_REGISTER_A_CC_CLASS]: '1 ',
  [ERR.CC_MODULE_KEY_CC_FOUND]: '1',
  [ERR.CC_MODULE_NAME_INVALID]: `1 `,
  [ERR.CC_STORE_STATE_INVALID]: `1 `,
  [ERR.CC_MODULE_REDUCER_IN_CC_CONFIGURE_OPTION_IS_INVALID]: `1`,
  [ERR.CC_REDUCER_IN_CC_CONFIGURE_OPTION_IS_INVALID]: `1`,
  [ERR.CC_REDUCER_VALUE_IN_CC_CONFIGURE_OPTION_IS_INVALID]: `1`,
  [ERR.CC_WATCH_MODULE_INVALID_IN_STARTUP_OPTION]: `1`,
  [ERR.CC_MODULE_NOT_FOUND]: `1`,
  [ERR.CC_DISPATCH_STRING_INVALID]: `1`,
  [ERR.CC_DISPATCH_PARAM_INVALID]: `1`,
  [ERR.CC_NO_DISPATCHER_FOUND]: `1
  `,
  [ERR.CC_MODULE_NAME_HAS_NO_STATE]:`1`,

  [ERR.CC_CLASS_INSTANCE_KEY_DUPLICATE]: `1`,
  [ERR.CC_CLASS_INSTANCE_OPTION_INVALID]: '1',
  [ERR.CC_CLASS_INSTANCE_NOT_FOUND]: '1',
  [ERR.CC_CLASS_INSTANCE_METHOD_NOT_FOUND]: '1! ',
  [ERR.CC_CLASS_INSTANCE_CALL_WITH_ARGS_INVALID]: '1 ',
  [ERR.CC_CLASS_INSTANCE_MORE_THAN_ONE]: '1',
  [ERR.CC_ARG_STORED_KEYS_DUPLICATE_WITH_WATCHED_KEYS]: '1',
  [ERR.CC_CLASS_INSTANCE_NO_CC_KEY_SPECIFIED_WHEN_USE_STORED_KEYS]: '1',

  [ERR.CC_CLASS_KEY_DUPLICATE]: '1 ',
  [ERR.CC_CLASS_NOT_FOUND]: '1 ',
  [ERR.CC_CLASS_STORE_MODULE_INVALID]: '1',
  [ERR.CC_CLASS_REDUCER_MODULE_INVALID]: '1',
  [ERR.CC_CLASS_IS_NOT_ALLOWED_REGISTER_TO_A_SINGLE_CLASS_MODULE]: '1',
  [ERR.CC_CLASS_STATE_TO_PROP_MAPPING_INVALID]: '1',
  [ERR.CC_CLASS_KEY_FRAGMENT_NOT_ALLOWED]: '1',

  [ERR.CC_ARG_KEYS_NOT_AN_ARRAY]: `1`,
  [ERR.CC_ARG_KEYS_INCLUDE_NON_STRING_ELEMENT]: '1',

  [ERR.CC_REDUCER_ACTION_TYPE_NAMING_INVALID]: `1`,
  [ERR.CC_REDUCER_ACTION_TYPE_NO_MODULE]: `1`,
  [ERR.CC_REDUCER_MODULE_NAME_DUPLICATE]: `1`,
  [ERR.CC_REDUCER_ACTION_TYPE_DUPLICATE]: `1`,
  [ERR.CC_REDUCER_NOT_A_FUNCTION]: `1`,

  // [ERR.REDUCER_KEY_NOT_EXIST_IN_STORE_MODULE]: `reducer key is invalid, cause cc may not under module mode when you startup, or the store don't include the module name you defined in reducer keys!`,
}

export default {
  MODULE_GLOBAL,
  MODULE_DEFAULT,
  MODULE_CC,
  ERR,
  ERR_MESSAGE,

  STATE_FOR_ONE_CC_INSTANCE_FIRSTLY,
  STATE_FOR_ALL_CC_INSTANCES_OF_ONE_MODULE,
}
